pom.xml
=> [프로젝트생성] 프로젝트 초기 파일 생성

src/main/java/com/projectteam/coop/util/SSHConnection.java, src/main/java/com/projectteam/coop/util/SSHContextListener.java
=> [프로젝트 설정] SSH 설정 값 조회 수정

src/test/java/com/projectteam/coop/util/SSHConnectionTest.java
=> [프로젝트 설정] SSH 터널링 테스트 코드 추가

pom.xml, src/main/resources/console-appender.xml, src/main/resources/file-error-appender.xml, src/main/resources/file-info-appender.xml, src/main/resources/file-warn-appender.xml, src/main/resources/logback.xml
=> [프로젝트 설정] 로깅 설정 수정(slf4j, logback)

src/main/resources/static/css/fragments/layoutIndexPage.css, src/main/resources/templates/index.html
index layout_Mok 추가
해당 index css부분 추가
추가한 layoutIndexPage.css부분 html에 추가
=> Add_index_layout_Mok

src/main/java/com/projectteam/coop/controller/PostController.java, src/main/java/com/projectteam/coop/controller/PostForm.java, src/main/java/com/projectteam/coop/repository/PostRepository.java, src/main/java/com/projectteam/coop/service/PostService.java, src/main/java/com/projectteam/coop/util/Paging.java, src/main/resources/templates/posts/createPostForm.html, src/main/resources/templates/posts/postList.html
=> [게시판 기능] 게시물 목록, 등록 추가

src/main/java/com/projectteam/coop/controller/PostController.java, src/main/java/com/projectteam/coop/controller/PostForm.java, src/main/java/com/projectteam/coop/repository/PostRepository.java, src/main/java/com/projectteam/coop/service/PostService.java, src/main/resources/static/js/common.js, src/main/resources/templates/fragments/bodyHeader.html, src/main/resources/templates/fragments/footer.html, src/main/resources/templates/fragments/header.html, src/main/resources/templates/posts/postInfo.html, src/main/resources/templates/posts/postList.html, src/main/resources/templates/posts/updatePostForm.html
=> [게시판 기능] 게시물 상세조회, 수정 추가

src/main/java/com/projectteam/coop/repository/post/PostRepository.java, src/main/java/com/projectteam/coop/sample/mybatis/service/SampleServiceImpl.java, src/main/java/com/projectteam/coop/service/post/PostService.java, src/main/java/com/projectteam/coop/web/menu/MenuController.java, src/main/java/com/projectteam/coop/web/post/PostController.java, src/main/java/com/projectteam/coop/web/post/PostForm.java
=> [프로젝트 설정] 디렉토리 구조 변경

pom.xml, src/main/java/com/projectteam/coop/domain/Comment.java, src/main/java/com/projectteam/coop/domain/Member.java, src/main/java/com/projectteam/coop/domain/MemberStatus.java, src/main/java/com/projectteam/coop/domain/Post.java, src/main/java/com/projectteam/coop/repository/member/MemberRepository.java, src/main/java/com/projectteam/coop/sample/mybatis/web/SampleController.java, src/main/java/com/projectteam/coop/service/member/MemberService.java, src/main/java/com/projectteam/coop/web/HomeController.java, src/main/java/com/projectteam/coop/web/login/LoginController.java, src/main/java/com/projectteam/coop/web/member/MemberController.java, src/main/java/com/projectteam/coop/web/member/MemberForm.java, src/main/java/com/projectteam/coop/web/session/SessionConst.java, src/main/resources/static/js/common.js, src/main/resources/templates/fragments/bodyHeader.html, src/main/resources/templates/fragments/loginBodyHeader.html, src/main/resources/templates/login/loginForm.html, src/main/resources/templates/loginIndex.html, src/main/resources/templates/members/createMemberForm.html
=> [회원 기능] 회원 가입, 로그인 추가

src/main/java/com/projectteam/coop/tft/domain/LeagueEntry.java, src/main/java/com/projectteam/coop/tft/domain/MatchDesc.java, src/main/java/com/projectteam/coop/tft/domain/MatchDescId.java, src/main/java/com/projectteam/coop/tft/domain/Summoner.java, src/main/java/com/projectteam/coop/tft/domain/Synergy.java, src/main/java/com/projectteam/coop/tft/domain/UsedAugment.java, src/main/java/com/projectteam/coop/tft/domain/UsedUnit.java, src/main/java/com/projectteam/coop/tft/repository/SynergyRepository.java, src/main/java/com/projectteam/coop/tft/service/LeagueEntryService.java, src/main/java/com/projectteam/coop/tft/service/MatchDescService.java, src/main/java/com/projectteam/coop/tft/service/SynergyService.java, src/main/java/com/projectteam/coop/web/menu/MenuController.java
domain Setter관련 수정
어노테이션 @Setter에서 함수로 Setter관리
=> <수정> 도메인 세터 관리형태 변경

src/main/java/com/projectteam/coop/domain/Member.java, src/main/java/com/projectteam/coop/domain/Product.java, src/main/java/com/projectteam/coop/domain/ProductStatus.java, src/main/java/com/projectteam/coop/domain/ProductType.java, src/main/java/com/projectteam/coop/domain/PurchaseList.java, src/main/java/com/projectteam/coop/repository/product/ProductRepository.java, src/main/java/com/projectteam/coop/service/product/ProductService.java, src/main/java/com/projectteam/coop/web/login/LoginController.java, src/main/java/com/projectteam/coop/web/member/MemberController.java, src/main/java/com/projectteam/coop/web/product/ProductController.java, src/main/java/com/projectteam/coop/web/product/ProductForm.java, src/main/java/com/projectteam/coop/web/session/SessionConst.java, src/main/java/com/projectteam/coop/web/shop/ShopController.java, src/main/resources/templates/admin/main.html, src/main/resources/templates/fragments/bodyHeader.html, src/main/resources/templates/fragments/loginBodyHeader.html, src/main/resources/templates/login/adminLoginForm.html, src/main/resources/templates/products/createProductForm.html, src/main/resources/templates/products/productList.html, src/main/resources/templates/products/shop.html, src/main/resources/templates/products/updateProductForm.html
=> [상품 기능] 상품 목록, 등록 추가

src/main/java/com/projectteam/coop/domain/Member.java, src/main/java/com/projectteam/coop/domain/PurchaseList.java, src/main/java/com/projectteam/coop/repository/member/MemberRepository.java, src/main/java/com/projectteam/coop/repository/purchaselist/PurchaseListRepository.java, src/main/java/com/projectteam/coop/service/login/LoginService.java, src/main/java/com/projectteam/coop/service/member/MemberService.java, src/main/java/com/projectteam/coop/service/purchaselist/PurchaseListService.java, src/main/java/com/projectteam/coop/web/HomeController.java, src/main/java/com/projectteam/coop/web/login/LoginController.java, src/main/java/com/projectteam/coop/web/order/OrderController.java, src/main/java/com/projectteam/coop/web/product/ProductController.java, src/main/resources/static/js/common.js, src/main/resources/templates/fragments/loginBodyHeader.html, src/main/resources/templates/orders/orderList.html, src/main/resources/templates/products/shop.html
=> [상품 기능] 상품 구매, 구매 조회 추가

src/main/java/com/projectteam/coop/web/menu/MenuController.java, src/main/resources/static/css/fragments/layoutChampionListPage.css, src/main/resources/static/css/fragments/layoutSynergyListPage.css, src/main/resources/static/css/fragments/tftContents.css, src/main/resources/static/js/tft/combination/combination.js, src/main/resources/templates/fragments/bodyHeader.html, src/main/resources/templates/fragments/loginBodyHeader.html, src/main/resources/templates/tft/combination.html
=> [페이지 추가] 조합 페이지 추가

src/main/java/com/projectteam/coop/domain/log/LoginLog.java, src/main/java/com/projectteam/coop/repository/log/LoginRepository.java, src/main/java/com/projectteam/coop/service/login/LoginService.java, src/main/java/com/projectteam/coop/web/login/LoginController.java
로그인 이력기반으로 포인트 적립하는거 추가했으니 확인해줘
=> [로그인 기능] 일별 포인트 적립 추가

src/main/java/com/projectteam/coop/domain/Post.java, src/main/java/com/projectteam/coop/domain/PostStatus.java, src/main/java/com/projectteam/coop/service/post/PostService.java, src/main/java/com/projectteam/coop/web/post/PostController.java, src/main/resources/templates/posts/createPostForm.html, src/main/resources/templates/posts/postList.html
게시판 목록 화면이랑 상세정보 볼 때 조회수 증가하도록 수정했으니 확인해줘
=> [게시판 기능] 게시물 목록표시 정보 수정 및 조회수 증가 추가

src/main/java/com/projectteam/coop/web/menu/MenuController.java, src/main/resources/static/css/fragments/layoutGuidePage.css, src/main/resources/static/css/fragments/tftContents.css, src/main/resources/templates/fragments/bodyHeader.html, src/main/resources/templates/fragments/loginBodyHeader.html, src/main/resources/templates/tft/guide.html
=> [페이지 추가] 가이드 페이지 추가

src/main/resources/templates/orders/orderList.html, src/main/resources/templates/products/shop.html
=> [상품 기능] 상품관련 화면 디자인 수정

src/main/java/com/projectteam/coop/web/HomeController.java, src/main/java/com/projectteam/coop/web/member/MemberController.java, src/main/java/com/projectteam/coop/web/post/PostController.java, src/main/java/com/projectteam/coop/web/shop/ShopController.java
세션 검증하는 부분 변경했고 입력 폼에서 검증 조건 추가했으니 확인해줘
=> [리팩토링] 세션 검증 변경 및 입력 폼 검증 추가

pom.xml, src/main/java/com/projectteam/coop/web/InitDb.java
=> [프로젝트 설정] 샘플 데이터 추가 및 라이브러리 추가

src/main/java/com/projectteam/coop/repository/member/MemberRepository.java, src/main/java/com/projectteam/coop/service/member/MemberService.java, src/main/java/com/projectteam/coop/web/member/MemberForm.java
=> [회원 기능] 회원 조회 추가

src/main/java/com/projectteam/coop/web/menu/MenuController.java, src/main/java/com/projectteam/coop/web/tft/SummonerController.java, src/main/resources/static/css/fragments/bodyHeader.css, src/main/resources/static/js/tft/bodyHeader.js, src/main/resources/templates/fragments/bodyHeader.html, src/main/resources/templates/index.html, src/main/webapp/WEB-INF/spring/root-context.xml
=> [기능 추가] 헤더, Home 페이지 , 서머너 검색기능 추가

src/main/java/com/projectteam/coop/util/TftUtil.java, src/main/java/com/projectteam/coop/web/menu/MenuController.java, src/main/java/com/projectteam/coop/web/tft/SummonerController.java
=> [Riot ApiKey수정] String -> properties

src/main/java/com/projectteam/coop/web/menu/MenuController.java, src/main/resources/static/js/tft/bodyHeader.js, src/main/resources/templates/index.html, src/main/resources/templates/tft/augmentsList.html, src/main/resources/templates/tft/championList.html, src/main/resources/templates/tft/combination.html, src/main/resources/templates/tft/guide.html, src/main/resources/templates/tft/summoner.html, src/main/resources/templates/tft/summonerSearchError.html, src/main/resources/templates/tft/synergyList.html
검색 에러 페이지 추가 및 TFT관련 html footer.html부분 추가
=> [기능 추가] 검색 에러 페이지 추가 및 TFT관련 html footer.html부분 추가

src/main/java/com/projectteam/coop/web/HomeController.java, src/main/java/com/projectteam/coop/web/argumentresolver/AdminLogin.java, src/main/java/com/projectteam/coop/web/argumentresolver/AdminLoginMemberArgumentResolver.java, src/main/java/com/projectteam/coop/web/argumentresolver/Login.java, src/main/java/com/projectteam/coop/web/argumentresolver/LoginMemberArgumentResolver.java, src/main/java/com/projectteam/coop/web/interceptor/LoginCheckInterceptor.java, src/main/java/com/projectteam/coop/web/login/LoginController.java, src/main/java/com/projectteam/coop/web/order/OrderController.java, src/main/resources/templates/admin/main.html, src/main/resources/templates/products/createProductForm.html, src/main/resources/templates/products/productList.html, src/main/resources/templates/products/shop.html, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/spring/root-context.xml
애노테이션 기반으로 로그인 세션 확인하는 거 추가하고 인터셉터 로직 수정했으니 확인해줘
=> [로그인 기능] 로그인 인터셉터 수정, 로그인 관련 Argument Resolver 추가

src/main/java/com/projectteam/coop/web/config/ErrorController.java, src/main/resources/templates/error-page/error.html, src/main/webapp/WEB-INF/web.xml
=> [프로젝트 설정] 에러 페이지 추가

src/main/java/com/projectteam/coop/tft/domain/MatchDesc.java, src/main/java/com/projectteam/coop/tft/service/MatchDescService.java, src/main/java/com/projectteam/coop/util/TftUtil.java, src/main/java/com/projectteam/coop/web/menu/MenuController.java, src/main/java/com/projectteam/coop/web/menu/summonerPageForm/SommonerMatchDescForm.java, src/main/java/com/projectteam/coop/web/menu/summonerPageForm/UserDesc.java, src/main/java/com/projectteam/coop/web/tft/SummonerController.java, src/main/resources/static/css/bootstrap/theme.css, src/main/resources/static/css/fragments/sumonner.css, src/main/resources/static/css/fragments/tftContents.css, src/main/resources/templates/fragments/header.html, src/main/resources/templates/tft/summoner.html
소환사 페이지 디자인 수정
경기 기록에서 소환사 닉네임 클릭할시 해당 소환사 검색 진행
=> [소환사 페이지 수정] 디자인, 기능 수정

src/main/java/com/projectteam/coop/web/menu/MenuController.java, src/main/java/com/projectteam/coop/web/menu/summonerPageForm/SommonerMatchDescForm.java, src/main/java/com/projectteam/coop/web/menu/summonerPageForm/SummonerForm.java, src/main/java/com/projectteam/coop/web/tft/SummonerController.java, src/main/resources/static/js/tft/summoner/summoner.js, src/main/resources/templates/tft/summoner.html
순방 횟수에 대한 기능 추가
더보기 버튼 기능 추가
-> DB안에 표시되어져있는 데이터 최대 10게임을 추가로 표시
-> 불러온 데이터가 10게임 이하면 해당 버튼 비표시화
=> [소환사 페이지 수정 및 기능추가]

src/main/java/com/projectteam/coop/domain/BaseEntity.java, src/main/java/com/projectteam/coop/domain/Comment.java, src/main/java/com/projectteam/coop/repository/comment/CommentRepository.java, src/main/java/com/projectteam/coop/service/comment/CommentService.java, src/main/java/com/projectteam/coop/web/comment/CommentController.java, src/main/java/com/projectteam/coop/web/post/CommentCreateForm.java, src/main/java/com/projectteam/coop/web/post/PostController.java, src/main/resources/templates/posts/postInfo.html
게시물 상세화면에서 댓글 등록하는 기능 추가했으니 확인해줘
=> [댓글 기능] 댓글 등록 및 화면 추가

src/main/resources/templates/fragments/bodyHeader.html, src/main/resources/templates/index.html
소환사 검색 앞 의문 공백 부분 수정
index.html 에서 커뮤니티 인기글 에리어 디자인 수정
=> [화면 디자인 변경]

src/main/java/com/projectteam/coop/repository/post/PostRepository.java, src/main/java/com/projectteam/coop/service/post/PostService.java, src/main/java/com/projectteam/coop/web/HomeController.java, src/main/resources/templates/index.html
=> [메인화면 기능] 커뮤니티 인기글 목록 표시 추가

src/main/java/com/projectteam/coop/domain/Post.java, src/main/java/com/projectteam/coop/repository/post/PostRepository.java, src/main/java/com/projectteam/coop/service/post/PostService.java, src/main/java/com/projectteam/coop/web/post/PostController.java, src/test/java/com/projectteam/coop/service/post/PostServiceTest.java
답글 등록 시 순서 꼬여서 게시판 쿼리 변경했고 테스트 코드 추가했으니 확인해줘
=> [게시판 기능] 테스트 코드 추가, 게시물 목록 조회, 답글 순서 쿼리 변경, 답글 생성자 수정

src/main/java/com/projectteam/coop/repository/log/LoginRepository.java, src/main/java/com/projectteam/coop/service/login/LoginService.java, src/test/java/com/projectteam/coop/service/login/LoginServiceTest.java
로그인 시 포인트 추가되는 부분 테스트 코드 추가했으니 확인해줘
=> [로그인 기능] 테스트 코드 추가, 불필요 코드 제거

src/main/java/com/projectteam/coop/domain/Member.java, src/main/java/com/projectteam/coop/repository/member/MemberRepository.java, src/main/java/com/projectteam/coop/service/member/MemberService.java, src/main/java/com/projectteam/coop/web/member/MemberController.java, src/test/java/com/projectteam/coop/service/member/MemberServiceTest.java
테스트 코드 추가했고 중복 이메일 가입안되도록 처리했으니 확인해줘
=> [회원 기능] 테스트 코드 추가, 중복 회원 검사 추가, 불필요 코드 제거

src/main/java/com/projectteam/coop/exception/MisMatchedPasswordException.java, src/main/java/com/projectteam/coop/repository/comment/CommentRepository.java, src/main/java/com/projectteam/coop/service/comment/CommentService.java, src/main/java/com/projectteam/coop/web/comment/CommentController.java, src/main/java/com/projectteam/coop/web/exhandler/advice/ExControllerAdvice.java, src/test/java/com/projectteam/coop/service/comment/CommentServiceTest.java
댓글 추가, 대댓글 추가, 댓글 삭제 관련해서 테스트 코드, 댓글 삭제 시 예외 처리도 추가했으니 확인해줘
=> [댓글 기능] 테스트 코드 추가 및 예외 조건 추가, 댓글 순서 쿼리 변경

src/main/java/com/projectteam/coop/domain/Product.java, src/main/java/com/projectteam/coop/domain/PurchaseList.java, src/main/java/com/projectteam/coop/repository/purchaselist/PurchaseListRepository.java, src/main/java/com/projectteam/coop/service/purchaselist/PurchaseListService.java, src/test/java/com/projectteam/coop/service/purchaselist/PurchaseListServiceTest.java
회원 상품 구매 테스트 코드 추가했고 비즈니스 로직 수정했으니 확인해줘
=> [상품 기능] 테스트 코드 추가, 상품 구매 비즈니스 로직 수정

src/main/java/com/projectteam/coop/domain/Post.java, src/main/java/com/projectteam/coop/repository/post/PostRepository.java, src/main/java/com/projectteam/coop/service/post/PostService.java, src/main/java/com/projectteam/coop/web/post/PostController.java, src/main/java/com/projectteam/coop/web/post/PostSearch.java, src/main/java/com/projectteam/coop/web/post/PostSearchType.java, src/main/resources/templates/posts/postList.html, src/test/java/com/projectteam/coop/service/post/PostServiceTest.java
=> [게시판 기능] 게시물 검색 기능 추가, 테스트 코드 수정

src/main/resources/templates/fragments/footer.html, src/main/resources/templates/index.html, src/main/resources/templates/orders/orderList.html, src/main/resources/templates/posts/postList.html, src/main/resources/templates/tft/augmentsList.html, src/main/resources/templates/tft/championList.html, src/main/resources/templates/tft/combination.html, src/main/resources/templates/tft/guide.html, src/main/resources/templates/tft/summoner.html, src/main/resources/templates/tft/summonerSearchError.html, src/main/resources/templates/tft/synergyList.html
=> [리팩토링] 푸터 내용 및 위치 수정

src/main/resources/templates/fragments/footer.html, src/main/resources/templates/fragments/header.html, src/main/resources/templates/index.html, src/main/resources/templates/layouts/baseLayout.html, src/main/resources/templates/login/adminLoginForm.html, src/main/resources/templates/login/loginForm.html, src/main/resources/templates/mail/forgotPassword.html, src/main/resources/templates/mail/mailResultPage.html, src/main/resources/templates/members/createMemberForm.html, src/main/resources/templates/members/updateMemberForm.html, src/main/resources/templates/orders/orderList.html, src/main/resources/templates/posts/createPostForm.html, src/main/resources/templates/posts/passwordForm.html, src/main/resources/templates/posts/postInfo.html, src/main/resources/templates/posts/postList.html, src/main/resources/templates/posts/replyPostForm.html, src/main/resources/templates/posts/updatePostForm.html, src/main/resources/templates/products/shop.html, src/main/resources/templates/tft/augmentsList.html, src/main/resources/templates/tft/championList.html, src/main/resources/templates/tft/combination.html, src/main/resources/templates/tft/guide.html, src/main/resources/templates/tft/summoner.html, src/main/resources/templates/tft/summonerSearchError.html, src/main/resources/templates/tft/synergyList.html
=> [디자인 수정] 페이지 레이아웃 추가 및 적용

src/main/java/com/projectteam/coop/api/CommentApiController.java, src/main/java/com/projectteam/coop/api/OrderApiController.java, src/main/java/com/projectteam/coop/api/PostApiController.java, src/main/java/com/projectteam/coop/web/InitDb.java
=> [프로젝트 설정] API 컨트롤러 분리, 초기 데이터 수정
